unit TestuFormulaUtils;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Classes, uFormulaUtils;

type
  // Test methods for class TFormula

  TestTFormula = class(TTestCase)
  published
    procedure TestDecode;
  end;

implementation
uses Variants;



{ TestTFormula }

procedure TestTFormula.TestDecode;
begin
  CheckEquals('a', Decode('x',['y','z','x','a','b']));
  CheckEquals('c', Decode('x',['y','a','c']));
  Check('' = Decode('x',['y','a']), 'erer');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFormula.Suite);
end.

